---
apiVersion: apps.open-cluster-management.io/v1
kind: HelmRelease
metadata:
  name: mongodb-chart
repo:
  chartName: mongodb
  source:
    github:
      chartPath: /bitnami/mongodb/
      urls:
        - https://github.com/bitnami/charts.git
    type: git
spec:
  replicaCount: 1
