---
apiVersion: apps.open-cluster-management.io/v1
kind: HelmRelease
metadata:
  name: nignx-new-fadin
repo:
  chartName: bitnami/mongodb
  source:
    helmRepo:
      urls:
        - https://charts.bitnami.com/bitnami
    type: helmrepo
  version: 10.9.1
spec:
  replicaCount: 2
