---
apiVersion: apps.open-cluster-management.io/v1
kind: HelmRelease
metadata:
  name: mongodb-weekdone
  namespace: weekdone-db
repo:
  chartName: weekdone-db
  source:
    helmRepo:
      urls:
        - https://raw.githubusercontent.com/open-cluster-management/multicloud-operators-subscription-release/main/test/helmrepo/nginx-chart-0.1.0.tgz
    type: helmrepo
  version: 0.1.0
spec:
  replicaCount: 3
